# create environment : conda env create -f environment.yml
# update dependencies: conda env update -f environment.yml
# remove environment : conda env remove -n elastic_py
# enter  environment : conda activate elastic_py
# exit   environment : conda deactivate
name: elastic_py
channels:
 - conda-forge
 - anaconda
 - defaults
dependencies:
 - numpy~=1.26.4
 - python>=3.9
 - matplotlib
 - scipy
 - xarray
 - gmt
 - pygmt
 - pip
 - jinja2=3.0.3
 - jupyterlab
 - jupyter
 - cutde~=22.3.17
 - pip:
    - Tectonic-Utils 
